name: 电信营业厅签到

on:
  watch:
    types: [ started ]
  schedule:
    - cron: 5 23 * * *
#  push:
#    branches: [ master ]

jobs:
  holl189:
    if: ${{ github.actor == 'Celeter' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: slave

      - name: Nodejs Install
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Requests Install
        run: npm install
        working-directory: Javascript

      - name: Script Run
        run: node 10000.js
        working-directory: Javascript
        env:
          TELECOM_MOBILE: ${{ secrets.TELECOM_MOBILE }}
