# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京小超领蓝币

on:
  push:
    branches:
      - master
  schedule:
    - cron: "10 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: slave
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        working-directory: Javascript/MyActions
        run: |
          npm install
      - name: "运行【京小超领蓝币(小费)】"
        working-directory: Javascript/MyActions
        run: |
          node onlyOneExecute.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          JDMarketCoinToBeans: ${{ secrets.JDMarketCoinToBeans }}
          SYNCURL: https://github.com/lxk0301/scripts/raw/master/jd_blueCoin.js
