name: 京东每日签到

on:
  watch:
    types: [ started ]
  schedule:
    - cron: 20 16 * * *
#  push:
#    branches: [ master ]
    
jobs:
  start:
    if: ${{ github.actor == 'Celeter' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: slave

      - name: Nodejs Install
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Requests Install
        run: npm install
        working-directory: Javascript

      - name: Script Run
        run: node JD_DailyBonus.js
        working-directory: Javascript
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          # PUSH_KEY: ${{ secrets.SCKEY }}
